# Generated by Django 2.2.4 on 2019-09-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('Titulo', models.CharField(max_length=80)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Anuncio', models.TextField()),
                ('nome_contato', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=10)),
                ('secao', models.CharField(max_length=10)),
                ('tipo_anuncio', models.CharField(max_length=100)),
            ],
        ),
    ]
